[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# Uncomment this if you want SPA-style redirects (not usually needed for Astro)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

